services:
    app-database:
        image: postgres:14
        container_name: postgres-postr-db
        ports:
            - "5432:5432"
        volumes:
            - db_app_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
            interval: 30s
            timeout: 20s
            retries: 3
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: oauth_test
    keycloak:
        image: ghcr.io/kon-bikas/keycloak-event-spi:latest
        command: [ "start-dev" , "--import-realm" ]
        container_name: keycloak-idp
        ports:
            - "9090:8080"
            - "9091:8081"
        depends_on:
            rabbit:
                condition: service_healthy
        volumes:
            - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
            - ./keycloak/import.json:/opt/keycloak/data/import/import.json
            - ./keycloak/keycloak-server.crt.pem:/opt/keycloak/certs/keycloak-server.crt.pem
            - ./keycloak/keycloak-server.key.pem:/opt/keycloak/certs/keycloak-server.key.pem
    rabbit:
        image: rabbitmq:4.1-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_VHOST: service
        volumes:
            -   ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            -   ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "ping"]
            interval: 5s
            timeout: 5s
            retries: 10
    minio:
        image: quay.io/minio/minio
        container_name: minio-storage
        #        command: ["server", "/data", "--console-address", ":9001"]
        entrypoint: /bin/bash
        command: -c "mkdir -p /data/media && /usr/bin/minio server /data"
        ports:
            -   "9000:9000"
            -   "9001:9001"
        environment:
            MINIO_ADDRESS: ":9000"
            MINIO_CONSOLE_ADDRESS: ":9001"
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            -   minio_data:/data
    spring:
        image: ghcr.io/kon-bikas/post-app:latest
        container_name: post-application
        ports:
            -   "8080:8080"
        depends_on:
            app-database:
                condition: service_healthy
            rabbit:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f" , "http://localhost:8080/actuator/health"]
            interval: 20s
            timeout: 10s
            retries: 3
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://app-database:5432/oauth_test
            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/demo-realm
            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/demo-realm/protocol/openid-connect/certs
            SPRING_RABBITMQ_HOST: rabbit
            SPRING_PROFILES_ACTIVE: dev
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            APP_MINIO_HOST_IP: minio
            APP_KEYCLOAK_SERVER_URL: http://keycloak:8080
            APP_KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_SECRET}

volumes:
    db_app_data:
    minio_data:

