apiVersion: v1
kind: Service
metadata:
    name: nginx-np-svc
    namespace: default
    labels:
        app: nginx
spec:
    selector:
        app: nginx
    type: NodePort
    ports:
        - name: nginx-np-port
          protocol: TCP
          port: 32555
          nodePort: 31666
          targetPort: 80
