apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: default
    labels:
        app: nginx
spec:
    selector:
        app: nginx
    type: ClusterIP
    ports:
        - name: nginx-http
          protocol: TCP
          port: 7777
          targetPort: ngx-http