apiVersion: v1
kind: Service
metadata:
    name: minio-np-svc
    namespace: default
    labels:
        app: minio
spec:
    selector:
        app: minio
    type: NodePort
    ports:
        - name: minio-console-port
          protocol: TCP
          port: 9001
          nodePort: 30112
          targetPort: minio-console