# Bootstrap admin configuration
bootstrap-admin-username=admin
bootstrap-admin-password=admin

# Custom event listener spi configuration
spi-events-listener-test-listener-enabled=true
spi-events-listener-test-listener-rabbit-host=rabbit
spi-events-listener-test-listener-rabbit-port=5672
spi-events-listener-test-listener-rabbit-username=admin
spi-events-listener-test-listener-rabbit-password=admin
spi-events-listener-test-listener-rabbit-exchange=app.exchange
spi-events-listener-test-listener-rabbit-virtual-host=service

# TLS/HTTPS certificates configuration
https-certificate-file=/opt/keycloak/certs/keycloak-server.crt.pem
https-certificate-key-file=/opt/keycloak/certs/keycloak-server.key.pem
https-port=8081

# Health/Monitoring
health-enabled=true