apiVersion: v1
kind: Service
metadata:
    name: psql-np-svc
    namespace: default
    labels:
        app: db
        db: psql
spec:
    selector:
        app: psql
    type: NodePort
    ports:
        - name: psql-np-port
          protocol: TCP
          port: 32112
          nodePort: 32222
          targetPort: psql-port
