apiVersion: v1
kind: Service
metadata:
    name: spring-np-svc
    namespace: default
    labels:
        app: spring
spec:
    selector:
        app: postr-app
    type: NodePort
    ports:
        - name: spring-np-port
          protocol: TCP
          port: 8080
          nodePort: 30111
          targetPort: postr-port