apiVersion: v1
kind: Pod
metadata:
    name: debug
    namespace: default
    labels:
        app: debug
spec:
    containers:
        - name: debug-container
          image: ubuntu:24.04
          command: ["sleep", "10000"]
          volumeMounts:
              - name: test-volume
                mountPath: /home/test
              - name: config-volume
                mountPath: /home/config
    volumes:
        - name: test-volume
          emptyDir:
              sizeLimit: 100Mi
        - name: config-volume
          configMap:
              name: debug-cm
              items:
                  - key: config.values
                    path: mypath
                  - key: other.values
                    path: other-path


